Modified fetch_resources.sh to add interface to alternate internal network
trilioData/tempest pull request #254
Opened 2022-02-17 08:23 UTC by priyankagupte15

Modified fetch_resources.sh to add interface to alternate internal network

2022-02-17 12:08 UTC, nasharatm requested changes

2022-02-17 12:08 UTC, nasharatm commented on fetch_resources.sh
>              network_id=`($OPENSTACK_CMD network list | grep test_internal_network | awk '$2 && $2 != "ID" {print $2}')`
This command fails on setups with different internal network. Ex => rhosp, we use 'trilio-internal-network'

2022-02-17 12:25 UTC, priyankagupte15 commented on fetch_resources.sh
>              network_id=`($OPENSTACK_CMD network list | grep test_internal_network | awk '$2 && $2 != "ID" {print $2}')`
This command will only run if not network is found on openstack. the in the previous step it created internal network with test_internal_network name and then we run this command to get id.
For setup which has internal network created this step will not be executed and network id will be picked up irrespective of network name

2022-02-17 12:41 UTC, nasharatm commented on fetch_resources.sh
>              network_id=`($OPENSTACK_CMD network list | grep test_internal_network | awk '$2 && $2 != "ID" {print $2}')`
looks good

2022-02-17 12:41 UTC, nasharatm approved these changes

2022-02-18 07:11 UTC, savitha-p requested changes

2022-02-18 07:11 UTC, savitha-p commented on fetch_resources.sh
> +            $OPENSTACK_CMD flavor create --ram 4096 --disk 20 --vcpus 2 $TEST_IMAGE_NAME
Revert this change. Looks like you need to pull latest changes from upstream.

2022-02-21 07:29 UTC, priyankagupte15 commented on fetch_resources.sh
> +            $OPENSTACK_CMD flavor create --ram 4096 --disk 20 --vcpus 2 $TEST_IMAGE_NAME
reverted the change

2022-02-21 07:31 UTC, savitha-p approved these changes

2022-02-21 07:31 UTC, merged