Snapshot mount to run on all FRM instances provided
trilioData/tempest pull request #255
Opened 2022-02-22 04:39 UTC by priyankagupte15

2022-02-23 13:42 UTC, nasharatm requested changes

2022-02-23 13:42 UTC, nasharatm commented on tempest/prerequisites.py
>          self.total_vms = 1
Please attach execution report for both centos and ubuntu frm? 
Please check "fvm_ssh_user = centos" field in tempest.conf

2022-02-23 13:42 UTC, nasharatm commented on tempest/api/workloadmgr/snapshot/test_snapshot_mount.py
> +                            LOG.debug("file does not found on FVM instacne")
Please check spell in few of LOG.debug statements.

2022-02-23 13:42 UTC, nasharatm commented on tempest/api/workloadmgr/snapshot/test_snapshot_mount.py
> +    # def test_2_umount_snapshot(self):
remove commented code.

2022-03-01 07:46 UTC, priyankagupte15 commented on tempest/api/workloadmgr/snapshot/test_snapshot_mount.py
> +    # def test_2_umount_snapshot(self):
done

2022-03-01 07:47 UTC, priyankagupte15 commented on tempest/prerequisites.py
>          self.total_vms = 1
http://192.168.1.62:8080/job/TrialJobs/job/PriyankaTrial/job/Ansible_Ubuntu20_Victoria-1_Func/30/HTML_20Report/
updated in script

2022-03-01 07:53 UTC, priyankagupte15 commented on tempest/api/workloadmgr/snapshot/test_snapshot_mount.py
> +                            LOG.debug("file does not found on FVM instacne")
updated

2022-03-01 09:10 UTC, nasharatm approved these changes

2022-03-01 12:40 UTC, savitha-p approved these changes

2022-03-01 12:40 UTC, merged