Automation fixes for rhosp failures for stable/4.2
trilioData/tempest pull request #266
Opened 2022-03-31 10:01 UTC by nasharatm

2022-03-31 10:06 UTC, savitha-p commented on tempest/util/query_data.py
> +        #get_snapshot_restore_id = ("select id from restores where snapshot_id='" +
Remove the commented code.

2022-03-31 10:34 UTC, savitha-p approved these changes

2022-03-31 10:43 UTC, nasharatm commented on tempest/util/query_data.py
> +        #get_snapshot_restore_id = ("select id from restores where snapshot_id='" +
done

2022-04-04 12:34 UTC, SuhasTA4 requested changes

2022-04-04 12:34 UTC, SuhasTA4 commented on tempest/api/workloadmgr/restore/test_selectiverestore_defaultvalues.py
> +                self.md5_sum_after_selective_restore[str(floating_ip)] = {}
@nasharatm  -    At line no. 193 we are declaring ==> md5_sum_after_selective_restore = {} and copying data inside the same, at line no. 203 ==>  md5_sum_after_selective_restore[str(floating_ip)][str(
                        mount_point)] = temp_md5sum
                        
Then, why we are using (line no. 196) ==> self.md5_sum_after_selective_restore[str(floating_ip)] = {}. What is the use ?
Either, we need to copy it to self.md5_sum_after_selective_restore or we need to use just md5_sum_after_selective_restore[str(floating_ip)] = {} at line no. 196

Please correct me, if I missed anything/ misinterpreted anywhere....

2022-04-04 12:42 UTC, nasharatm commented on tempest/api/workloadmgr/restore/test_selectiverestore_defaultvalues.py
> +                self.md5_sum_after_selective_restore[str(floating_ip)] = {}
done changes

2022-04-05 05:20 UTC, SuhasTA4 approved these changes

2022-04-05 06:18 UTC, merged