OS-2020-workload edit with unencrypted and encrypted volume instances
trilioData/tempest pull request #278
Opened 2022-04-15 11:47 UTC by SuhasTA4

2022-04-15 11:48 UTC, SuhasTA4 commented
1. Create unencrypted volume 
2. Attached this unencrypted volume to vm created.
3. Create workload with unencrypted vm attached. 
4. Take snapshot of this workload. 
5. Create encrypted volume of type luks
6. Attach to newly created vm.
7. Do workload edit and add 1 more vm having encrypted volume attached
8. Workload edit should fail.
9. Verify proper error message is returned. 

![image](https://user-images.githubusercontent.com/98375572/163567275-beedc696-835c-4b31-9d45-d3cad55a1f68.png)

2022-04-18 05:15 UTC, savitha-p commented on tempest/api/workloadmgr/barbican/test_barbican.py
> +                if (vol.lower().find("luks") != -1):
Fetch both encrypted and unencrypted volume types at one time itself. If any of the volume type is not available, workload and snapshot steps can be skipped.

2022-04-18 05:18 UTC, savitha-p commented on tempest/api/workloadmgr/barbican/test_barbican.py
> +            except Exception as e:
This exception block does not get called here and error message verification gets skipped. Error msg verification need to be handled.

2022-04-18 05:20 UTC, savitha-p commented on tempest/api/workloadmgr/barbican/test_barbican.py
> +                                                workload_cleanup=True)
Add a test step of unencrypted workload creation success to test report.

2022-04-18 05:20 UTC, savitha-p commented on tempest/api/workloadmgr/barbican/test_barbican.py
> +                LOG.debug("Full snapshot created...")
Add test step of  full snapshot success to report

2022-04-18 07:38 UTC, nasharatm requested changes

2022-04-18 07:38 UTC, nasharatm commented on tempest/api/workloadmgr/barbican/test_barbican.py
> +                reporting.add_test_step("No unencrypted volume available to attach", tvaultconf.FAIL)
Please mention "volume type" instead of "volume"

2022-04-18 07:38 UTC, nasharatm commented on tempest/api/workloadmgr/barbican/test_barbican.py
> +            if (vol_type_id == -1):
change it to "volume type"

2022-04-18 07:38 UTC, nasharatm commented on tempest/api/workloadmgr/barbican/test_barbican.py
> +                    LOG.error("Command did not execute correctly")
Please capture the error thrown by command itself here. It would be helpful for verification as well.

2022-04-18 11:25 UTC, SuhasTA4 commented
![image](https://user-images.githubusercontent.com/98375572/163801668-6e95d373-1770-4c32-be6e-8bfc2ce4620c.png)

2022-04-18 13:20 UTC, SuhasTA4 commented
Changed test steps statements. 
![image](https://user-images.githubusercontent.com/98375572/163814021-ca8aedae-0e64-4f0f-b05e-b400b7f59d79.png)

2022-04-18 13:56 UTC, nasharatm approved these changes

2022-04-18 16:02 UTC, savitha-p approved these changes

2022-04-18 16:02 UTC, merged