AUTO-165: MOSK functional run failure analysis and fixes - stable/5.0
trilioData/tempest pull request #344
Opened 2022-07-15 13:21 UTC by SuhasTA4

2022-07-15 15:15 UTC, savitha-p commented
Please attach local test run results for these tests

2022-07-18 18:01 UTC, SuhasTA4 commented
Attaching tempest.log snippet for each test showing test case PASS after handling scenarios like, 
- snapshot delete
- workload delete
- restore delete
![image](https://user-images.githubusercontent.com/98375572/179573793-3fa31eab-7c03-49e1-8f2e-aab2f4e1d57c.png)

2022-07-19 05:03 UTC, savitha-p requested changes
Comments added

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/workload/test_workload.py
> +                        LOG.debug("Returned value deleted for workload deletion status. Not Expected return value.")
This should be logged as error.

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/workload/test_workload.py
> +                        LOG.debug("Returned value error for workload deletion status. Failed to delete Workload")
This should be logged as error.

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/snapshot/test_snapshots.py
>                  reporting.add_test_step("Verification", tvaultconf.PASS)
If 1 is returned, verification should be marked as fail.

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/workload/test_workload.py
> +                    time.sleep(30)
Reduce the sleep time

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/restore/test_tvault1290_delete_restore.py
> +            max_retries = 20
Add max_retries to tvaultconf.py and use that in the script.

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/workload/test_workload.py
> +                max_retries = 20
Add max_retries to tvaultconf.py and use that in the script.

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/restore/test_tvault1290_delete_restore.py
>              if (str(wc) == "1"):
If 1 status is returned, then verification should fail

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/restore/test_tvault1040_oneclick_restore.py
> +            max_retries = 20
Add max_retries to tvaultconf.py and use that in the script.

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/restore/test_tvault1040_oneclick_restore.py
> +                time.sleep(30)
Reduce sleep time to may be 15sec

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/restore/test_tvault1040_oneclick_restore.py
> +                    LOG.debug("Failed to restore snapshot")
This should be logged as error

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/restore/test_tvault1037_list_restore.py
> +                    LOG.debug("Failed to restore snapshot.")
This should be logged as error

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/restore/test_tvault1037_list_restore.py
> +            max_retries = 20
Add max_retries to tvaultconf.py and use that in the script.

2022-07-19 05:03 UTC, savitha-p commented on tempest/api/workloadmgr/restore/test_tvault1037_list_restore.py
> +                time.sleep(30)
Reduce sleep time to 15sec

2022-07-19 07:17 UTC, savitha-p approved these changes

2022-07-19 07:20 UTC, priyankagupte15 approved these changes

2022-07-19 07:23 UTC, nasharatm approved these changes

2022-07-19 07:29 UTC, merged