AUTO-221 & AUTO-222 - workload reassignment OS-2063 and OS-2064
trilioData/tempest pull request #382
Opened 2022-09-13 17:37 UTC by SuhasTA4

2022-09-13 17:40 UTC, SuhasTA4 commented
AUTO-221 result:
![image](https://user-images.githubusercontent.com/98375572/189972649-da4258d7-7394-49af-9e60-fb7275a019b4.png)

2022-09-13 17:40 UTC, SuhasTA4 commented
AUTO-222 result:
![image](https://user-images.githubusercontent.com/98375572/189972785-9816f192-b348-4081-9378-dbe01c347bfa.png)

2022-09-14 05:35 UTC, priyankagupte15 commented on tempest/api/workloadmgr/workload_reassign/test_workload_reassign.py
> +            project_details = self.create_project(project_cleanup=True)
since default cleanup value is True, parameter can be removed

2022-09-14 05:35 UTC, priyankagupte15 commented on tempest/api/workloadmgr/workload_reassign/test_workload_reassign.py
> +                [vm_id], tvaultconf.parallel, workload_cleanup=True)
since default cleanup value is True, parameter can be removed

2022-09-14 05:35 UTC, priyankagupte15 commented on tempest/api/workloadmgr/workload_reassign/test_workload_reassign.py
> +            project_details = self.create_project(project_cleanup=True)
since default cleanup value is True, parameter can be removed

2022-09-14 05:35 UTC, priyankagupte15 commented on tempest/api/workloadmgr/workload_reassign/test_workload_reassign.py
> +                [vm_id], tvaultconf.parallel, workload_cleanup=True)
since default cleanup value is True, parameter can be removed

2022-09-14 05:58 UTC, priyankagupte15 approved these changes

2022-09-14 06:35 UTC, nasharatm requested changes

2022-09-14 06:35 UTC, nasharatm commented on tempest/api/workloadmgr/workload_reassign/test_workload_reassign.py
> +                    "Workload reassign with temp project and temp user", tvaultconf.PASS)
workload reassign fails in this case, hence need to add similar statement in reporting with result as "Pass".
EX => workload reassign on temp deleted project failed => Result : Pass

2022-09-14 06:48 UTC, SuhasTA4 commented
New Report for AUTO-221
![image](https://user-images.githubusercontent.com/98375572/190080860-0c791acc-2398-497b-a81e-d72d45b3f040.png)

2022-09-14 06:50 UTC, nasharatm approved these changes

2022-09-14 06:50 UTC, merged